image: docker.slock.it/build-images/node:11-alpine
variables:
  COMMIT_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - test
  - package
  - analysis
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build-in3:
  stage: build
  tags:
    - short-jobs
  script:
    - sh /prepare.sh
    - npm install
    - npm run build
  artifacts:
    paths:
      - js/

test-in3:
  stage: test
  tags:
    - short-jobs
  script:
    - sh /prepare.sh
    - npm install
    - npm test

  artifacts:
    name: "test-reports-$CI_JOB_NAME"
    paths:
      - test/report

test-implementation:
  stage: test
  tags:
    - short-jobs
  script:
    - sh /prepare.sh
    - npm install
    - npm run build
    - npm test
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/in3/ts/in3-implementation-tests.git
    - cd in3-implementation-tests
    - npm install
    - cd node_modules
    - ln -s ../../ in3
    - cd ..
    - npm run build-ts

test-in3-examples:
  stage: test
  tags:
    - short-jobs
  script:
    - sh /prepare.sh
    - cd examples/
    - npm install
    - rm -rf node_modules/in3
    - cd ..
    - npm i && npm run build
    - mkdir examples/node_modules/in3
    - cp -r `ls -A | grep -v "examples"` examples/node_modules/in3/
    - cd examples/
    - npm run start

test-usn-lib:
  stage: test
  tags:
    - short-jobs
  allow_failure: true
  variables:
    RPCURL: http://parity:8545
    USN_TESTMODE: parity
    TEST_RESULTS: test/results/parity/
    TEST_SCOPE: short
  services:
    - name: parity/parity:stable
      command:
        - --jsonrpc-experimental
        - --jsonrpc-apis=all
        - --logging=3
        - --jsonrpc-interface=all
        - --ws-interface=all
        - --chain=dev
        - --gas-cap=8000000
        - --gasprice=0
        - --reseal-min-period=0
        - --gas-floor-target=8700000
        - --tracing=on
      alias: parity
  script:
    - sh /prepare.sh
    - npm install
    - npm run build
    - cd ..
    - rm -rf usn-testing
    - mkdir usn-testing
    - cd usn-testing
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@git.slock.it/iotlayer/usn-lib.git --single-branch
    - cd usn-lib
    - npm install
    - rm -rf node_modules/in3
    - cd node_modules
    - ln -s /builds/in3/ts/in3 in3
    - cd ..

deploy-docker:
  stage: package
  tags:
    - short-jobs
  services:
    - docker:dind
  image: docker.slock.it/build-images/deployment
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $COMMIT_IMAGE_TAG .
    - docker tag $COMMIT_IMAGE_TAG $RELEASE_IMAGE_TAG
    - docker push $RELEASE_IMAGE_TAG
    - docker push $COMMIT_IMAGE_TAG

vulnerabilities:
  stage: analysis
  tags:
    - short-jobs
  dependencies:
    - deploy-docker
  allow_failure: true
  image: docker.slock.it/build-images/vulnerability-testing-tools
  script:
    - export TRIVY_AUTH_URL=$CI_REGISTRY
    - export TRIVY_USERNAME=gitlab-ci-token
    - export TRIVY_PASSWORD=$CI_JOB_TOKEN
    - trivy -f json -o vulnerability_analysis.json --exit-code 1 $COMMIT_IMAGE_TAG
  artifacts:
    paths:
      - vulnerability_analysis.json

deploy-to-slockit-npm:
  stage: deploy
  tags:
    - short-jobs
  only: # deploy only on  semantic versions tags
    - /^v[0-9]*\.[0-9]*\.[0-9]*-?.*$/
  except:
    - branches
  dependencies:
    - build-in3
  script:
    - sh /prepare.sh
    - npm --no-git-tag-version --allow-same-version -f version $CI_COMMIT_TAG
    - npm publish
